[package]
name = "raft-test"
version = "0.1.0"
authors = ["mpostma <postma.marin@protonmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
raft= "0.5.0"
futures = "0.3.5"
tokio = { version = "0.2", features = ["full"] }
tonic = "0.3.0"
log = { version = "0.4", features = ["std"] }
env_logger = "0.7.1"
serde = { version = "1.0.114", features = ["derive"] }
prost = "0.6.1"
bincode = "1.3"
protobuf = "2"

[build-dependencies]
tonic-build = "0.3.0"
